version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/www/next-static:/app/_next/static
    ports:
      - "9003:9003"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
