version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/www/next-static:/app/.next/static
    ports:
      - "9003:9003"
    environment:
      - NODE_ENV=production
      - BASE_PATH=restaurants
    restart: unless-stopped
